// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var ViewNames = struct {
	TagBrowserAuthors    string
	TagBrowserPublishers string
	TagBrowserRatings    string
	TagBrowserTags       string
}{
	TagBrowserAuthors:    "tag_browser_authors",
	TagBrowserPublishers: "tag_browser_publishers",
	TagBrowserRatings:    "tag_browser_ratings",
	TagBrowserTags:       "tag_browser_tags",
}
