// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Annotations         string
	Authors             string
	Books               string
	BooksAuthorsLink    string
	BooksLanguagesLink  string
	BooksPluginData     string
	BooksPublishersLink string
	BooksRatingsLink    string
	BooksSeriesLink     string
	BooksTagsLink       string
	Comments            string
	ConversionOptions   string
	CustomColumns       string
	Data                string
	Feeds               string
	Identifiers         string
	Languages           string
	LastReadPositions   string
	LibraryID           string
	Preferences         string
	Publishers          string
	Ratings             string
	Series              string
	Tags                string
}{
	Annotations:         "annotations",
	Authors:             "authors",
	Books:               "books",
	BooksAuthorsLink:    "books_authors_link",
	BooksLanguagesLink:  "books_languages_link",
	BooksPluginData:     "books_plugin_data",
	BooksPublishersLink: "books_publishers_link",
	BooksRatingsLink:    "books_ratings_link",
	BooksSeriesLink:     "books_series_link",
	BooksTagsLink:       "books_tags_link",
	Comments:            "comments",
	ConversionOptions:   "conversion_options",
	CustomColumns:       "custom_columns",
	Data:                "data",
	Feeds:               "feeds",
	Identifiers:         "identifiers",
	Languages:           "languages",
	LastReadPositions:   "last_read_positions",
	LibraryID:           "library_id",
	Preferences:         "preferences",
	Publishers:          "publishers",
	Ratings:             "ratings",
	Series:              "series",
	Tags:                "tags",
}
