// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// TagBrowserAuthor is an object representing the database table.
type TagBrowserAuthor struct {
	ID        null.Int64  `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	Name      null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	Count     null.String `boil:"count" json:"count,omitempty" toml:"count" yaml:"count,omitempty"`
	AvgRating null.String `boil:"avg_rating" json:"avg_rating,omitempty" toml:"avg_rating" yaml:"avg_rating,omitempty"`
	Sort      null.String `boil:"sort" json:"sort,omitempty" toml:"sort" yaml:"sort,omitempty"`
}

var TagBrowserAuthorColumns = struct {
	ID        string
	Name      string
	Count     string
	AvgRating string
	Sort      string
}{
	ID:        "id",
	Name:      "name",
	Count:     "count",
	AvgRating: "avg_rating",
	Sort:      "sort",
}

var TagBrowserAuthorTableColumns = struct {
	ID        string
	Name      string
	Count     string
	AvgRating string
	Sort      string
}{
	ID:        "tag_browser_authors.id",
	Name:      "tag_browser_authors.name",
	Count:     "tag_browser_authors.count",
	AvgRating: "tag_browser_authors.avg_rating",
	Sort:      "tag_browser_authors.sort",
}

// Generated where

var TagBrowserAuthorWhere = struct {
	ID        whereHelpernull_Int64
	Name      whereHelpernull_String
	Count     whereHelpernull_String
	AvgRating whereHelpernull_String
	Sort      whereHelpernull_String
}{
	ID:        whereHelpernull_Int64{field: "\"tag_browser_authors\".\"id\""},
	Name:      whereHelpernull_String{field: "\"tag_browser_authors\".\"name\""},
	Count:     whereHelpernull_String{field: "\"tag_browser_authors\".\"count\""},
	AvgRating: whereHelpernull_String{field: "\"tag_browser_authors\".\"avg_rating\""},
	Sort:      whereHelpernull_String{field: "\"tag_browser_authors\".\"sort\""},
}

var (
	tagBrowserAuthorAllColumns            = []string{"id", "name", "count", "avg_rating", "sort"}
	tagBrowserAuthorColumnsWithoutDefault = []string{}
	tagBrowserAuthorColumnsWithDefault    = []string{"id", "name", "count", "avg_rating", "sort"}
	tagBrowserAuthorPrimaryKeyColumns     = []string{}
	tagBrowserAuthorGeneratedColumns      = []string{}
)

type (
	// TagBrowserAuthorSlice is an alias for a slice of pointers to TagBrowserAuthor.
	// This should almost always be used instead of []TagBrowserAuthor.
	TagBrowserAuthorSlice []*TagBrowserAuthor
	// TagBrowserAuthorHook is the signature for custom TagBrowserAuthor hook methods
	TagBrowserAuthorHook func(context.Context, boil.ContextExecutor, *TagBrowserAuthor) error

	tagBrowserAuthorQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tagBrowserAuthorType           = reflect.TypeOf(&TagBrowserAuthor{})
	tagBrowserAuthorMapping        = queries.MakeStructMapping(tagBrowserAuthorType)
	tagBrowserAuthorInsertCacheMut sync.RWMutex
	tagBrowserAuthorInsertCache    = make(map[string]insertCache)
	tagBrowserAuthorUpdateCacheMut sync.RWMutex
	tagBrowserAuthorUpdateCache    = make(map[string]updateCache)
	tagBrowserAuthorUpsertCacheMut sync.RWMutex
	tagBrowserAuthorUpsertCache    = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
	// These are used in some views
	_ = fmt.Sprintln("")
	_ = reflect.Int
	_ = strings.Builder{}
	_ = sync.Mutex{}
	_ = strmangle.Plural("")
	_ = strconv.IntSize
)

var tagBrowserAuthorAfterSelectMu sync.Mutex
var tagBrowserAuthorAfterSelectHooks []TagBrowserAuthorHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TagBrowserAuthor) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tagBrowserAuthorAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTagBrowserAuthorHook registers your hook function for all future operations.
func AddTagBrowserAuthorHook(hookPoint boil.HookPoint, tagBrowserAuthorHook TagBrowserAuthorHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		tagBrowserAuthorAfterSelectMu.Lock()
		tagBrowserAuthorAfterSelectHooks = append(tagBrowserAuthorAfterSelectHooks, tagBrowserAuthorHook)
		tagBrowserAuthorAfterSelectMu.Unlock()
	}
}

// OneG returns a single tagBrowserAuthor record from the query using the global executor.
func (q tagBrowserAuthorQuery) OneG(ctx context.Context) (*TagBrowserAuthor, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single tagBrowserAuthor record from the query.
func (q tagBrowserAuthorQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TagBrowserAuthor, error) {
	o := &TagBrowserAuthor{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for tag_browser_authors")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all TagBrowserAuthor records from the query using the global executor.
func (q tagBrowserAuthorQuery) AllG(ctx context.Context) (TagBrowserAuthorSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all TagBrowserAuthor records from the query.
func (q tagBrowserAuthorQuery) All(ctx context.Context, exec boil.ContextExecutor) (TagBrowserAuthorSlice, error) {
	var o []*TagBrowserAuthor

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TagBrowserAuthor slice")
	}

	if len(tagBrowserAuthorAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all TagBrowserAuthor records in the query using the global executor
func (q tagBrowserAuthorQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all TagBrowserAuthor records in the query.
func (q tagBrowserAuthorQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count tag_browser_authors rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q tagBrowserAuthorQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q tagBrowserAuthorQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if tag_browser_authors exists")
	}

	return count > 0, nil
}

// TagBrowserAuthors retrieves all the records using an executor.
func TagBrowserAuthors(mods ...qm.QueryMod) tagBrowserAuthorQuery {
	mods = append(mods, qm.From("\"tag_browser_authors\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"tag_browser_authors\".*"})
	}

	return tagBrowserAuthorQuery{q}
}
