// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// BooksSeriesLink is an object representing the database table.
type BooksSeriesLink struct {
	ID     null.Int64 `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	Book   int64      `boil:"book" json:"book" toml:"book" yaml:"book"`
	Series int64      `boil:"series" json:"series" toml:"series" yaml:"series"`

	R *booksSeriesLinkR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L booksSeriesLinkL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BooksSeriesLinkColumns = struct {
	ID     string
	Book   string
	Series string
}{
	ID:     "id",
	Book:   "book",
	Series: "series",
}

var BooksSeriesLinkTableColumns = struct {
	ID     string
	Book   string
	Series string
}{
	ID:     "books_series_link.id",
	Book:   "books_series_link.book",
	Series: "books_series_link.series",
}

// Generated where

var BooksSeriesLinkWhere = struct {
	ID     whereHelpernull_Int64
	Book   whereHelperint64
	Series whereHelperint64
}{
	ID:     whereHelpernull_Int64{field: "\"books_series_link\".\"id\""},
	Book:   whereHelperint64{field: "\"books_series_link\".\"book\""},
	Series: whereHelperint64{field: "\"books_series_link\".\"series\""},
}

// BooksSeriesLinkRels is where relationship names are stored.
var BooksSeriesLinkRels = struct {
}{}

// booksSeriesLinkR is where relationships are stored.
type booksSeriesLinkR struct {
}

// NewStruct creates a new relationship struct
func (*booksSeriesLinkR) NewStruct() *booksSeriesLinkR {
	return &booksSeriesLinkR{}
}

// booksSeriesLinkL is where Load methods for each relationship are stored.
type booksSeriesLinkL struct{}

var (
	booksSeriesLinkAllColumns            = []string{"id", "book", "series"}
	booksSeriesLinkColumnsWithoutDefault = []string{"book", "series"}
	booksSeriesLinkColumnsWithDefault    = []string{"id"}
	booksSeriesLinkPrimaryKeyColumns     = []string{"id"}
	booksSeriesLinkGeneratedColumns      = []string{"id"}
)

type (
	// BooksSeriesLinkSlice is an alias for a slice of pointers to BooksSeriesLink.
	// This should almost always be used instead of []BooksSeriesLink.
	BooksSeriesLinkSlice []*BooksSeriesLink
	// BooksSeriesLinkHook is the signature for custom BooksSeriesLink hook methods
	BooksSeriesLinkHook func(context.Context, boil.ContextExecutor, *BooksSeriesLink) error

	booksSeriesLinkQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	booksSeriesLinkType                 = reflect.TypeOf(&BooksSeriesLink{})
	booksSeriesLinkMapping              = queries.MakeStructMapping(booksSeriesLinkType)
	booksSeriesLinkPrimaryKeyMapping, _ = queries.BindMapping(booksSeriesLinkType, booksSeriesLinkMapping, booksSeriesLinkPrimaryKeyColumns)
	booksSeriesLinkInsertCacheMut       sync.RWMutex
	booksSeriesLinkInsertCache          = make(map[string]insertCache)
	booksSeriesLinkUpdateCacheMut       sync.RWMutex
	booksSeriesLinkUpdateCache          = make(map[string]updateCache)
	booksSeriesLinkUpsertCacheMut       sync.RWMutex
	booksSeriesLinkUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var booksSeriesLinkAfterSelectMu sync.Mutex
var booksSeriesLinkAfterSelectHooks []BooksSeriesLinkHook

var booksSeriesLinkBeforeInsertMu sync.Mutex
var booksSeriesLinkBeforeInsertHooks []BooksSeriesLinkHook
var booksSeriesLinkAfterInsertMu sync.Mutex
var booksSeriesLinkAfterInsertHooks []BooksSeriesLinkHook

var booksSeriesLinkBeforeUpdateMu sync.Mutex
var booksSeriesLinkBeforeUpdateHooks []BooksSeriesLinkHook
var booksSeriesLinkAfterUpdateMu sync.Mutex
var booksSeriesLinkAfterUpdateHooks []BooksSeriesLinkHook

var booksSeriesLinkBeforeDeleteMu sync.Mutex
var booksSeriesLinkBeforeDeleteHooks []BooksSeriesLinkHook
var booksSeriesLinkAfterDeleteMu sync.Mutex
var booksSeriesLinkAfterDeleteHooks []BooksSeriesLinkHook

var booksSeriesLinkBeforeUpsertMu sync.Mutex
var booksSeriesLinkBeforeUpsertHooks []BooksSeriesLinkHook
var booksSeriesLinkAfterUpsertMu sync.Mutex
var booksSeriesLinkAfterUpsertHooks []BooksSeriesLinkHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *BooksSeriesLink) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range booksSeriesLinkAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *BooksSeriesLink) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range booksSeriesLinkBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *BooksSeriesLink) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range booksSeriesLinkAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *BooksSeriesLink) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range booksSeriesLinkBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *BooksSeriesLink) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range booksSeriesLinkAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *BooksSeriesLink) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range booksSeriesLinkBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *BooksSeriesLink) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range booksSeriesLinkAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *BooksSeriesLink) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range booksSeriesLinkBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *BooksSeriesLink) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range booksSeriesLinkAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBooksSeriesLinkHook registers your hook function for all future operations.
func AddBooksSeriesLinkHook(hookPoint boil.HookPoint, booksSeriesLinkHook BooksSeriesLinkHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		booksSeriesLinkAfterSelectMu.Lock()
		booksSeriesLinkAfterSelectHooks = append(booksSeriesLinkAfterSelectHooks, booksSeriesLinkHook)
		booksSeriesLinkAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		booksSeriesLinkBeforeInsertMu.Lock()
		booksSeriesLinkBeforeInsertHooks = append(booksSeriesLinkBeforeInsertHooks, booksSeriesLinkHook)
		booksSeriesLinkBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		booksSeriesLinkAfterInsertMu.Lock()
		booksSeriesLinkAfterInsertHooks = append(booksSeriesLinkAfterInsertHooks, booksSeriesLinkHook)
		booksSeriesLinkAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		booksSeriesLinkBeforeUpdateMu.Lock()
		booksSeriesLinkBeforeUpdateHooks = append(booksSeriesLinkBeforeUpdateHooks, booksSeriesLinkHook)
		booksSeriesLinkBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		booksSeriesLinkAfterUpdateMu.Lock()
		booksSeriesLinkAfterUpdateHooks = append(booksSeriesLinkAfterUpdateHooks, booksSeriesLinkHook)
		booksSeriesLinkAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		booksSeriesLinkBeforeDeleteMu.Lock()
		booksSeriesLinkBeforeDeleteHooks = append(booksSeriesLinkBeforeDeleteHooks, booksSeriesLinkHook)
		booksSeriesLinkBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		booksSeriesLinkAfterDeleteMu.Lock()
		booksSeriesLinkAfterDeleteHooks = append(booksSeriesLinkAfterDeleteHooks, booksSeriesLinkHook)
		booksSeriesLinkAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		booksSeriesLinkBeforeUpsertMu.Lock()
		booksSeriesLinkBeforeUpsertHooks = append(booksSeriesLinkBeforeUpsertHooks, booksSeriesLinkHook)
		booksSeriesLinkBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		booksSeriesLinkAfterUpsertMu.Lock()
		booksSeriesLinkAfterUpsertHooks = append(booksSeriesLinkAfterUpsertHooks, booksSeriesLinkHook)
		booksSeriesLinkAfterUpsertMu.Unlock()
	}
}

// OneG returns a single booksSeriesLink record from the query using the global executor.
func (q booksSeriesLinkQuery) OneG(ctx context.Context) (*BooksSeriesLink, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single booksSeriesLink record from the query.
func (q booksSeriesLinkQuery) One(ctx context.Context, exec boil.ContextExecutor) (*BooksSeriesLink, error) {
	o := &BooksSeriesLink{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for books_series_link")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all BooksSeriesLink records from the query using the global executor.
func (q booksSeriesLinkQuery) AllG(ctx context.Context) (BooksSeriesLinkSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all BooksSeriesLink records from the query.
func (q booksSeriesLinkQuery) All(ctx context.Context, exec boil.ContextExecutor) (BooksSeriesLinkSlice, error) {
	var o []*BooksSeriesLink

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to BooksSeriesLink slice")
	}

	if len(booksSeriesLinkAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all BooksSeriesLink records in the query using the global executor
func (q booksSeriesLinkQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all BooksSeriesLink records in the query.
func (q booksSeriesLinkQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count books_series_link rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q booksSeriesLinkQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q booksSeriesLinkQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if books_series_link exists")
	}

	return count > 0, nil
}

// BooksSeriesLinks retrieves all the records using an executor.
func BooksSeriesLinks(mods ...qm.QueryMod) booksSeriesLinkQuery {
	mods = append(mods, qm.From("\"books_series_link\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"books_series_link\".*"})
	}

	return booksSeriesLinkQuery{q}
}

// FindBooksSeriesLinkG retrieves a single record by ID.
func FindBooksSeriesLinkG(ctx context.Context, iD null.Int64, selectCols ...string) (*BooksSeriesLink, error) {
	return FindBooksSeriesLink(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindBooksSeriesLink retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBooksSeriesLink(ctx context.Context, exec boil.ContextExecutor, iD null.Int64, selectCols ...string) (*BooksSeriesLink, error) {
	booksSeriesLinkObj := &BooksSeriesLink{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"books_series_link\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, booksSeriesLinkObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from books_series_link")
	}

	if err = booksSeriesLinkObj.doAfterSelectHooks(ctx, exec); err != nil {
		return booksSeriesLinkObj, err
	}

	return booksSeriesLinkObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *BooksSeriesLink) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *BooksSeriesLink) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no books_series_link provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(booksSeriesLinkColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	booksSeriesLinkInsertCacheMut.RLock()
	cache, cached := booksSeriesLinkInsertCache[key]
	booksSeriesLinkInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			booksSeriesLinkAllColumns,
			booksSeriesLinkColumnsWithDefault,
			booksSeriesLinkColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, booksSeriesLinkGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(booksSeriesLinkType, booksSeriesLinkMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(booksSeriesLinkType, booksSeriesLinkMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"books_series_link\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"books_series_link\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into books_series_link")
	}

	if !cached {
		booksSeriesLinkInsertCacheMut.Lock()
		booksSeriesLinkInsertCache[key] = cache
		booksSeriesLinkInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single BooksSeriesLink record using the global executor.
// See Update for more documentation.
func (o *BooksSeriesLink) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the BooksSeriesLink.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *BooksSeriesLink) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	booksSeriesLinkUpdateCacheMut.RLock()
	cache, cached := booksSeriesLinkUpdateCache[key]
	booksSeriesLinkUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			booksSeriesLinkAllColumns,
			booksSeriesLinkPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, booksSeriesLinkGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update books_series_link, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"books_series_link\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, booksSeriesLinkPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(booksSeriesLinkType, booksSeriesLinkMapping, append(wl, booksSeriesLinkPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update books_series_link row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for books_series_link")
	}

	if !cached {
		booksSeriesLinkUpdateCacheMut.Lock()
		booksSeriesLinkUpdateCache[key] = cache
		booksSeriesLinkUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q booksSeriesLinkQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q booksSeriesLinkQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for books_series_link")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for books_series_link")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o BooksSeriesLinkSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BooksSeriesLinkSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), booksSeriesLinkPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"books_series_link\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, booksSeriesLinkPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in booksSeriesLink slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all booksSeriesLink")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *BooksSeriesLink) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *BooksSeriesLink) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no books_series_link provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(booksSeriesLinkColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	booksSeriesLinkUpsertCacheMut.RLock()
	cache, cached := booksSeriesLinkUpsertCache[key]
	booksSeriesLinkUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			booksSeriesLinkAllColumns,
			booksSeriesLinkColumnsWithDefault,
			booksSeriesLinkColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			booksSeriesLinkAllColumns,
			booksSeriesLinkPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert books_series_link, could not build update column list")
		}

		ret := strmangle.SetComplement(booksSeriesLinkAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(booksSeriesLinkPrimaryKeyColumns))
			copy(conflict, booksSeriesLinkPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"books_series_link\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(booksSeriesLinkType, booksSeriesLinkMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(booksSeriesLinkType, booksSeriesLinkMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert books_series_link")
	}

	if !cached {
		booksSeriesLinkUpsertCacheMut.Lock()
		booksSeriesLinkUpsertCache[key] = cache
		booksSeriesLinkUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single BooksSeriesLink record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *BooksSeriesLink) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single BooksSeriesLink record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BooksSeriesLink) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no BooksSeriesLink provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), booksSeriesLinkPrimaryKeyMapping)
	sql := "DELETE FROM \"books_series_link\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from books_series_link")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for books_series_link")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q booksSeriesLinkQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q booksSeriesLinkQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no booksSeriesLinkQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from books_series_link")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for books_series_link")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o BooksSeriesLinkSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BooksSeriesLinkSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(booksSeriesLinkBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), booksSeriesLinkPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"books_series_link\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, booksSeriesLinkPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from booksSeriesLink slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for books_series_link")
	}

	if len(booksSeriesLinkAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *BooksSeriesLink) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no BooksSeriesLink provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BooksSeriesLink) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBooksSeriesLink(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BooksSeriesLinkSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty BooksSeriesLinkSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BooksSeriesLinkSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BooksSeriesLinkSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), booksSeriesLinkPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"books_series_link\".* FROM \"books_series_link\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, booksSeriesLinkPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BooksSeriesLinkSlice")
	}

	*o = slice

	return nil
}

// BooksSeriesLinkExistsG checks if the BooksSeriesLink row exists.
func BooksSeriesLinkExistsG(ctx context.Context, iD null.Int64) (bool, error) {
	return BooksSeriesLinkExists(ctx, boil.GetContextDB(), iD)
}

// BooksSeriesLinkExists checks if the BooksSeriesLink row exists.
func BooksSeriesLinkExists(ctx context.Context, exec boil.ContextExecutor, iD null.Int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"books_series_link\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if books_series_link exists")
	}

	return exists, nil
}

// Exists checks if the BooksSeriesLink row exists.
func (o *BooksSeriesLink) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return BooksSeriesLinkExists(ctx, exec, o.ID)
}
