// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// TagBrowserPublisher is an object representing the database table.
type TagBrowserPublisher struct {
	ID        null.Int64  `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	Name      null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	Count     null.String `boil:"count" json:"count,omitempty" toml:"count" yaml:"count,omitempty"`
	AvgRating null.String `boil:"avg_rating" json:"avg_rating,omitempty" toml:"avg_rating" yaml:"avg_rating,omitempty"`
	Sort      null.String `boil:"sort" json:"sort,omitempty" toml:"sort" yaml:"sort,omitempty"`
}

var TagBrowserPublisherColumns = struct {
	ID        string
	Name      string
	Count     string
	AvgRating string
	Sort      string
}{
	ID:        "id",
	Name:      "name",
	Count:     "count",
	AvgRating: "avg_rating",
	Sort:      "sort",
}

var TagBrowserPublisherTableColumns = struct {
	ID        string
	Name      string
	Count     string
	AvgRating string
	Sort      string
}{
	ID:        "tag_browser_publishers.id",
	Name:      "tag_browser_publishers.name",
	Count:     "tag_browser_publishers.count",
	AvgRating: "tag_browser_publishers.avg_rating",
	Sort:      "tag_browser_publishers.sort",
}

// Generated where

var TagBrowserPublisherWhere = struct {
	ID        whereHelpernull_Int64
	Name      whereHelpernull_String
	Count     whereHelpernull_String
	AvgRating whereHelpernull_String
	Sort      whereHelpernull_String
}{
	ID:        whereHelpernull_Int64{field: "\"tag_browser_publishers\".\"id\""},
	Name:      whereHelpernull_String{field: "\"tag_browser_publishers\".\"name\""},
	Count:     whereHelpernull_String{field: "\"tag_browser_publishers\".\"count\""},
	AvgRating: whereHelpernull_String{field: "\"tag_browser_publishers\".\"avg_rating\""},
	Sort:      whereHelpernull_String{field: "\"tag_browser_publishers\".\"sort\""},
}

var (
	tagBrowserPublisherAllColumns            = []string{"id", "name", "count", "avg_rating", "sort"}
	tagBrowserPublisherColumnsWithoutDefault = []string{}
	tagBrowserPublisherColumnsWithDefault    = []string{"id", "name", "count", "avg_rating", "sort"}
	tagBrowserPublisherPrimaryKeyColumns     = []string{}
	tagBrowserPublisherGeneratedColumns      = []string{}
)

type (
	// TagBrowserPublisherSlice is an alias for a slice of pointers to TagBrowserPublisher.
	// This should almost always be used instead of []TagBrowserPublisher.
	TagBrowserPublisherSlice []*TagBrowserPublisher
	// TagBrowserPublisherHook is the signature for custom TagBrowserPublisher hook methods
	TagBrowserPublisherHook func(context.Context, boil.ContextExecutor, *TagBrowserPublisher) error

	tagBrowserPublisherQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tagBrowserPublisherType           = reflect.TypeOf(&TagBrowserPublisher{})
	tagBrowserPublisherMapping        = queries.MakeStructMapping(tagBrowserPublisherType)
	tagBrowserPublisherInsertCacheMut sync.RWMutex
	tagBrowserPublisherInsertCache    = make(map[string]insertCache)
	tagBrowserPublisherUpdateCacheMut sync.RWMutex
	tagBrowserPublisherUpdateCache    = make(map[string]updateCache)
	tagBrowserPublisherUpsertCacheMut sync.RWMutex
	tagBrowserPublisherUpsertCache    = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
	// These are used in some views
	_ = fmt.Sprintln("")
	_ = reflect.Int
	_ = strings.Builder{}
	_ = sync.Mutex{}
	_ = strmangle.Plural("")
	_ = strconv.IntSize
)

var tagBrowserPublisherAfterSelectMu sync.Mutex
var tagBrowserPublisherAfterSelectHooks []TagBrowserPublisherHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TagBrowserPublisher) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tagBrowserPublisherAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTagBrowserPublisherHook registers your hook function for all future operations.
func AddTagBrowserPublisherHook(hookPoint boil.HookPoint, tagBrowserPublisherHook TagBrowserPublisherHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		tagBrowserPublisherAfterSelectMu.Lock()
		tagBrowserPublisherAfterSelectHooks = append(tagBrowserPublisherAfterSelectHooks, tagBrowserPublisherHook)
		tagBrowserPublisherAfterSelectMu.Unlock()
	}
}

// OneG returns a single tagBrowserPublisher record from the query using the global executor.
func (q tagBrowserPublisherQuery) OneG(ctx context.Context) (*TagBrowserPublisher, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single tagBrowserPublisher record from the query.
func (q tagBrowserPublisherQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TagBrowserPublisher, error) {
	o := &TagBrowserPublisher{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for tag_browser_publishers")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all TagBrowserPublisher records from the query using the global executor.
func (q tagBrowserPublisherQuery) AllG(ctx context.Context) (TagBrowserPublisherSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all TagBrowserPublisher records from the query.
func (q tagBrowserPublisherQuery) All(ctx context.Context, exec boil.ContextExecutor) (TagBrowserPublisherSlice, error) {
	var o []*TagBrowserPublisher

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TagBrowserPublisher slice")
	}

	if len(tagBrowserPublisherAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all TagBrowserPublisher records in the query using the global executor
func (q tagBrowserPublisherQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all TagBrowserPublisher records in the query.
func (q tagBrowserPublisherQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count tag_browser_publishers rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q tagBrowserPublisherQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q tagBrowserPublisherQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if tag_browser_publishers exists")
	}

	return count > 0, nil
}

// TagBrowserPublishers retrieves all the records using an executor.
func TagBrowserPublishers(mods ...qm.QueryMod) tagBrowserPublisherQuery {
	mods = append(mods, qm.From("\"tag_browser_publishers\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"tag_browser_publishers\".*"})
	}

	return tagBrowserPublisherQuery{q}
}
